Add <Nav /> Component
atoulous/green-tetris pull request #20
Opened 2018-02-17 18:01 UTC by jmunozz

# FRONTEND  

- Create a smart `<Nav />` component that wraps logic for modifying nickname.
- All nicknames changes are made through a modal dialog.
- Add new actions `UPDATE_NICKNAMES` and 2 actions related to the modal itself.
- Add new reducer functions for nickname and for the modal itself.

**todo**
_If player has already joined a game, nickname change must be notified to other players through the game object._

2018-02-18 11:08 UTC, thifranc commented on src/server/config/routes.js
> +    const gamesWaiting = allGames.filter(game => (!game.hasStarted));
allGames is deprecated, use getGames from handlers/games now

2018-02-18 11:12 UTC, thifranc commented on src/client/actions/tetris.js
> +  console.log('stickPieceDown');
nice eslint !

2018-02-18 11:17 UTC, thifranc reviewed
nice eslint
change components names as their not really explicit imo
e.g. : AllGames should be gamesList or Games
same for playersList
also why does gameSettings contains players, that would be separated I'd say as players aren't really a setting
fix conflicts and all good

2018-02-19 11:18 UTC, thifranc reviewed
Awesome !

2018-02-19 11:27 UTC, atoulous requested changes
just rename actionPlayer to actionsPlayer

2018-02-19 11:27 UTC, atoulous commented on src/client/actions/index.js
> +  ...actionPlayer,
actionS

2018-02-19 11:40 UTC, merged